# Generated by Django 4.1.1 on 2022-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='groupexpense',
            name='part_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
